name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker images 
      working-directory: demo/Dockerfile
      run: docker compose build

    - name: Run the docker compose
      working-directory: /demo-ui/Dockerfile
      run: docker compose up -d
