name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }} 

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3           

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests
        # mvn clean install -DskipTests # Build your Spring Boot app

    # - name: Upload jar
    #   run: yes | cp -rf -p /home/runner/work/demo/demo/target/demo-0.0.1-SNAPSHOT.jar target

    # - uses: actions/upload-artifact@v4
    #   with:
    #     name: demo
    #     path: target

    # - name: Get directory
    #   run: ls
            
    - name: login to DockerHub
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}


    - name: Build Docker Compose services
      run: docker compose build

    - name: Push Docker Compose images to Docker Hub
      run: docker compose push 

    - name: Pull Docker Compose images from Docker Hub
      run: docker compose pull 

      # - name: build the docker image method 1
    #   id: build-docker-image
    #   run: |
    #     ls -la 
    #     docker build . -f Dockerfile -t maxtheservice/demo:latest
    # - name: push the docker image
    #   id: push-docker-image
    #   run: docker push ${{secrets.DOCKERHUB_USERNAME}}/demo:latest

    # - name: Extract metadata (tags, labels) for Docker
    #   id: meta
    #   uses: docker/metadata-action@v5
    #   with:
    #        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}


    # - name: Build and Push to DockerHub method 2
    #   uses: docker/build-push-action@v6
    #   with:
    #     context: .
    #     push: true
    #     labels: ${{ steps.meta.outputs.labels }}   
    #     tags: maxtheservice/demo:latest
    #     # tags: ${{ steps.meta.outputs.tags }}
    #     # annotations: ${{ steps.meta.outputs.annotations }}     
      


























    - name: check images before pull
      run: docker images

    # - name: pull the image
    #   run: docker pull maxtheservice/demo:latest

    # - name: check images after pull
    #   run: docker images

    # - name: Inspect
    #   run: |
    #     docker image inspect maxtheservice/demo:latest      
    # - name: remove all services
    #   run: docker compose down --rmi all # remove all containers

    # - name: Run Docker Container
    #   run: docker run -p 8080:80 --name demo-container maxtheservice/demo:latest      

    # - name: check containers
    #   run: docker ps

    # - name: remove all services
    #   run: docker compose down --rmi all # remove all containers

    # - name: Start Docker Compose services
    #   run: docker compose up --build # Build and start containers
    # # - name: Wait for MySQL to be ready
    # #   run: |
    # #     for i in $(seq 1 10); do
    # #       docker-compose exec mysql mysqladmin ping -h localhost --silent && break
    # #       echo "Waiting for MySQL..."
    # #       sleep 5
    # #     done
    # - name: Run integration tests
    #   run: mvn test # Run tests against the running services
    # - name: Stop Docker Compose services
    #   run: docker-compose down
